In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'Loves Popcorn': ['Yes', 'Yes', 'No', 'No',
                                'Yes', 'Yes', 'No'],
             'Loves Soda' : ['Yes', 'No', 'Yes', 'Yes',
                           'Yes', 'No', 'No'],
             'Age' : [7, 12, 18, 35, 38, 50, 83],
             'Loves Cool As Ice' : ['No', 'No', 'Yes', 'Yes',
                                    'Yes', 'No', 'No']})

In [3]:
#replace categorical columns into numerical
for col in df.columns:
    if df[col].dtype == 'object':
        #df[col].replace(df[col].unique().tolist(), range(0, len(df[col].unique())), inplace=True)
        df[col].replace(['No', 'Yes'], range(0, 2), inplace=True)

In [4]:
print(df)

   Loves Popcorn  Loves Soda  Age  Loves Cool As Ice
0              1           1    7                  0
1              1           0   12                  0
2              0           1   18                  1
3              0           1   35                  1
4              1           1   38                  1
5              1           0   50                  0
6              0           0   83                  0


In [5]:
np_data = np.array(df)

In [41]:
len(np.unique(np_data[:, 2]))

7

In [138]:
gini_values = []
for column in range(3):
    print(len(np.unique(np_data[:, column])))
    gini_impurity = 0
    total_samples_in_leaf = len(np_data[:, column])
    weighted_impurity = 0.0
    #if column is categorical
    if len(np.unique(np_data[:, column])) == 2:
        for target in np.unique(np_data[:, -1]):
            yes =np.sum( (np_data[:, column] == 0) & (np_data[:, -1] == target))
            no = np.sum( (np_data[:, column] == 1) & (np_data[:, -1] == target))

            weighted_gini = (sum([yes, no]) /total_samples_in_leaf)
            gini_impurity = 1 - (yes  / (yes + no))**2 - (no  / (yes + no))**2
            weighted_impurity += gini_impurity* weighted_gini
        print(f'weighted_impurity : {weighted_impurity:.3f}')
        gini_values.append(weighted_impurity)
    #if column is continuous
    else:
        lowest_gini = 1
        picked_value = 0
        sorted_values = np.sort(np_data[:, column])
        average_values = [ (sorted_values[i] + sorted_values[i-1])/2  for i in range(1, len(sorted_continuous_values))]
        for value in average_values:
            for i in range(2):    
                if i == 0:
                    yes =np.sum( (sorted_values < value) & (np_data[:, -1] == 1))
                    no = np.sum( (sorted_values < value) & (np_data[:, -1] == 0))
                else:
                    yes =np.sum( (sorted_values > value) & (np_data[:, -1] == 1))
                    no = np.sum( (sorted_values > value) & (np_data[:, -1] == 0))
                weighted_gini = (sum([yes, no]) /total_samples_in_leaf)
                gini_impurity = 1 - (yes  / (yes + no))**2 - (no  / (yes + no))**2
                weighted_impurity += gini_impurity* weighted_gini
            print(f'weighted_impurity : {weighted_impurity:.3f}')
            #save lowest gini value and column value 
            if weighted_impurity < lowest_gini:
                picked_value = value
                lowest_gini = weighted_impurity
            weighted_impurity = 0.0
        gini_values.append(lowest_gini)
    print('-------------------------')
print(f'gini_values: {np.round(gini_values, 3)}')

2
weighted_impurity : 0.405
-------------------------
2
weighted_impurity : 0.214
-------------------------
7
weighted_impurity : 0.429
weighted_impurity : 0.343
weighted_impurity : 0.476
weighted_impurity : 0.476
weighted_impurity : 0.343
weighted_impurity : 0.429
-------------------------
gini_values: [0.405 0.214 0.343]


In [113]:
np.sum( (sorted_values > value) & (np_data[:, -1] == target))


3

In [110]:
target

1

In [109]:
sorted_values < value, np_data[:,-1]

(array([ True, False, False, False, False, False, False]),
 array([0, 0, 1, 1, 1, 0, 0], dtype=int64))

In [25]:
total_samples_in_leaf

[0.5714285714285714, 0.42857142857142855]

In [24]:
gini_impurity

[0.375, 0.4444444444444445]

In [92]:
sorted_values
value = 9.5

In [97]:
sorted_values < value

array([ True, False, False, False, False, False, False])

In [84]:
x= np.sum((sorted_values < value) & (np_data[:, -1] == 1))
y= np.sum((sorted_values > value) & (np_data[:, -1] == 1))
print(x, y)

0 3
